# This file helps us easily spin up our Postgres and Redis databases in local
# development (this is not meant to be used in production), bypassing the need
# to install and configure these services on our local machines.

services:
  browserless:
    container_name: hackalumni-browserless
    image: ghcr.io/browserless/chromium
    ports:
      - 3333:3000

  postgres:
    container_name: hackalumni-postgres
    image: postgres:15-alpine
    ports:
      # We're using port 5433 to avoid any potential conflicts.
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hackalumni
      POSTGRES_PASSWORD: hackalumni
      POSTGRES_USER: hackalumni

  postgres-test:
    container_name: hackalumni-postgres-test
    image: postgres:15-alpine
    ports:
      # We're using port 5434 to avoid any potential conflicts.
      - 5434:5432
    environment:
      POSTGRES_DB: hackalumni_test
      POSTGRES_PASSWORD: hackalumni
      POSTGRES_USER: hackalumni

  redis:
    container_name: hackalumni-redis
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
