# Render configuration for Hack Alumni Community monorepo
# This file defines all the services that will be deployed to Render using Docker

services:
  # API Service
  - type: web
    name: hack-alumni-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: yarn workspace @hackcommunity/api start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: POSTMARK_API_TOKEN
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false
      - key: QSTASH_TOKEN
        sync: false
      - key: QSTASH_CURRENT_SIGNING_KEY
        sync: false
      - key: QSTASH_NEXT_SIGNING_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ENVIRONMENT
        value: production

  # Admin Dashboard Service
  - type: web
    name: hack-alumni-admin-dashboard
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: yarn workspace @hackcommunity/admin-dashboard start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: API_BASE_URL
        value: https://hack-alumni-api.onrender.com

  # Member Profile Service
  - type: web
    name: hack-alumni-member-profile
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: yarn workspace @hackcommunity/member-profile start
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: API_BASE_URL
        value: https://hack-alumni-api.onrender.com
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
